# Generated by Django 5.2.7 on 2025-10-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_accent',
            field=models.CharField(default='retail', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_primary_color',
            field=models.CharField(default='#14b8a6', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_welcome_message',
            field=models.CharField(default="Hi there! I'm your ShoshChat assistant.", max_length=255),
        ),
    ]
