version: "3.10"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shoshchat
      POSTGRES_USER: shoshchat
      POSTGRES_PASSWORD: shoshchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  worker:
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
volumes:
  postgres_data:
