# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('industry', models.CharField(choices=[
                    ('retail', 'Retail'),
                    ('ecommerce', 'E-commerce'),
                    ('saas', 'SaaS'),
                    ('professional_services', 'Professional Services'),
                    ('healthcare', 'Healthcare'),
                    ('education', 'Education'),
                    ('real_estate', 'Real Estate'),
                    ('hospitality', 'Hospitality'),
                    ('finance', 'Finance'),
                    ('other', 'Other'),
                ], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('trial_ends', models.DateField(blank=True, null=True)),
                ('widget_welcome_message', models.CharField(default='Hi there! How can I help you today?', max_length=255)),
                ('widget_primary_color', models.CharField(default='#14b8a6', max_length=7)),
                ('widget_position', models.CharField(choices=[
                    ('bottom-right', 'Bottom Right'),
                    ('bottom-left', 'Bottom Left'),
                ], default='bottom-right', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[
                    ('admin', 'Admin'),
                    ('manager', 'Manager'),
                    ('member', 'Member'),
                ], default='member', max_length=16)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_business_user'),
        ),
    ]
